export const CITY_TO_LOCATION_TEXT: Record<string, string> = {
  'vinnytska-oblast': 'у Вінницькій області',
  'volynska-oblast': 'у Волинській області',
  'dnipropetrovska-oblast': 'у Дніпропетровській області',
  'zhytomyrska-oblast': 'у Житомирській області',
  'zakarpatska-oblast': 'у Закарпатській області',
  'zaporizka-oblast': 'у Запорізькій області',
  'ivano-frankivska-oblast': 'в Івано-Франківській області',
  'kyivska-oblast': 'у Київській області',
  'kirovohradska-oblast': 'у Кіровоградській області',
  'lvivska-oblast': 'у Львівській області',
  'mykolaivska-oblast': 'у Миколаївській області',
  'odeska-oblast': 'в Одеській області',
  'poltavska-oblast': 'у Полтавській області',
  'rivnenska-oblast': 'у Рівненській області',
  'sumska-oblast': 'у Сумській області',
  'ternopilska-oblast': 'у Тернопільській області',
  'kharkivska-oblast': 'у Харківській області',
  'khersonska-oblast': 'у Херсонській області',
  'khmelnytska-oblast': 'у Хмельницькій області',
  'cherkaska-oblast': 'у Черкаській області',
  'chernihivska-oblast': 'у Чернігівській області',
  'chernivetska-oblast': 'у Чернівецькій області',
  kyiv: 'в Києві',
};
