export const REGION_CITY_SLUGS = [
  'vinnytska-oblast',
  'volynska-oblast',
  'dnipropetrovska-oblast',
  'zhytomyrska-oblast',
  'zakarpatska-oblast',
  'zaporizka-oblast',
  'ivano-frankivska-oblast',
  'kyivska-oblast',
  'kirovohradska-oblast',
  'lvivska-oblast',
  'mykolaivska-oblast',
  'odeska-oblast',
  'poltavska-oblast',
  'rivnenska-oblast',
  'sumska-oblast',
  'ternopilska-oblast',
  'kharkivska-oblast',
  'khersonska-oblast',
  'khmelnytska-oblast',
  'cherkaska-oblast',
  'chernihivska-oblast',
  'chernivetska-oblast',
  'kyiv',
] as const;
